### ISSUE TITLE
Error: mvn install fails for injecting: in.virit.vwscdn.VWSCDNMojo

### ISSUE THREAD

**Issue by OscarAlmgren** [samie/bluemix-mqtt-dashboard#1]
I just did a git clone based on the instructions from the README. 

The mvn install step fails 
`Downloaded: https://repo.maven.apache.org/maven2/com/vaadin/vaadin-server/7.4.1/vaadin-server-7.4.1.jar (3215 KB at 651.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/vaadin/vaadin-themes/7.4.1/vaadin-themes-7.4.1.jar (7241 KB at 752.7 KB/sec)
[INFO] 
[INFO] --- vwscdn-maven-plugin:1.3.3:generate (default-generate) @ bluemix-mqtt-dashboard --
[WARNING] Error injecting: in.virit.vwscdn.VWSCDNMojo
java.lang.TypeNotPresentException: Type in.virit.vwscdn.VWSCDNMojo not present`

The provided error code is 

```
[ERROR] Failed to execute goal in.virit.vwscdn:vwscdn-maven-plugin:1.3.3:generate (default-generate) on project bluemix-mqtt-dashboard: Execution default-generate of goal in.virit.vwscdn:vwscdn-maven-plugin:1.3.3:generate failed: Unable to load the mojo 'generate' in the plugin 'in.virit.vwscdn:vwscdn-maven-plugin:1.3.3' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: in/virit/vwscdn/VWSCDNMojo : Unsupported major.minor version 51.0
```

I don't know enough of how the code works to fix this and create a pull request for a fix.

**Comment by samie** [comment]
Looks like Java 7  issue. What Java version you are using with Maven? You can check that with:

```
 mvn -version
```

**Comment by OscarAlmgren** [comment]
Java 1.6.
Output:

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
```

I'll have a look and see if updating to 1.7+ helps.

Update: solved it.
Also link: http://stackoverflow.com/questions/18813828/why-maven-use-jdk-1-6-but-my-java-version-is-1-7
